### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by zooool** [NellielProject/Nelliel#13]
```
2023/08/16 21:49:21 [error] 8607#8607: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table `nelliel`.`nelliel_r9k_mutes` (errno: 121 "Duplicate key on write or update") in /var/www/html/core/include/Tables/Table.php:218
Stack trace:
#0 /var/www/html/core/include/Tables/Table.php(218): PDO->query()
#1 /var/www/html/core/include/Tables/Table.php(29): Nelliel\Tables\Table->createTableQuery()
#2 /var/www/html/core/include/Setup/Setup.php(292): Nelliel\Tables\Table->createTable()
#3 /var/www/html/core/include/Setup/Setup.php(118): Nelliel\Setup\Setup->createCoreTables()
#4 /var/www/html/core/include/initializations.php(19): Nelliel\Setup\Setup->install()
#5 /var/www/html/imgboard.php(43): require_once('...')
#6 {main}
  thrown in /var/www/html/core/include/Tables/Table.php on line 218" while reading response header from upstream, client: xxx, server: _, request: "POST /imgboard.php?install HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "xxx", referrer: "http://xxx/imgboard.php?install"
```

**Comment by OtakuMegane** [comment]
Patched in some fixes so installation should be working now. The installer is getting an overhaul in the next version (can be found in `dev-general` branch).
